### ISSUE TITLE
"Multiple build commands" warning for header files

### ISSUE THREAD

**Issue by jpmhouston** [Blue-Rocket/BRFullTextSearch#12]
Can something be done to avoid these warnings? We're wanting to turn on "Treat Warnings as Errors" and this is now our only blocker to that.

```
Warning: Multiple build commands for output file .../Build/Products/Debug-iphonesimulator/BRFullTextSearch.framework/Headers/_FastCharStream.h
Warning: Multiple build commands for output file .../Build/Products/Debug-iphonesimulator/BRFullTextSearch.framework/Headers/libstemmer.h
Warning: Multiple build commands for output file .../Build/Products/Debug-iphonesimulator/BRFullTextSearch.framework/Headers/Scorer.h
```

My predecessor created a seemingly drastic work-around to prevent these warnings, adding the following to the Podfile. I'm less comfortable with this approach, however, and hope there's a better solution.

``` ruby
  # Whether this is the fault of CocoaPods or BRFullTextSearch or Xcode, the
  # simplest workaround is to delete the copy headers build phase. This might
  # normally break a build due to missing headers, but CocoaPods copies all
  # headers to Pods/Headers during integration and configures search paths to
  # look there first, so the headers remain available. Given that, this script
  # deletes the copy headers build phase from all the CocoaPods targets.
  installer.pod_targets.each do |target|
    target.native_target.build_phases.reject! { |bp| bp.is_a?(Xcodeproj::Project::Object::PBXHeadersBuildPhase) } if !target.native_target.nil?
  end
```

**Comment by msqr** [comment]
CLucene has multiple files in different directories named the same, and when building in Xcode all headers are copied flat into the build dir, causing this error. There are [open tickets on CocoaPods](https://github.com/CocoaPods/CocoaPods/issues/4496) for this problem. I have not found a way around this issue myself, but welcome any PR that can find a way to address it.

You could  build `BRFullTextSearch` as a static framework and include that in your project, instead of using CocoaPods, which I believe would eliminate the warnings for you.

**Comment by msqr** [comment]
Closing issue; feel free to re-open if you find a way to work around the issue.
