### ISSUE TITLE
Migration to use BRCLucene question

### ISSUE THREAD

**Issue by gfzabarino** [Blue-Rocket/BRFullTextSearch#24]
How come we have 4f9ea38 (and its later merge to master) if the CLucene code is now in a different pod/project? Looks like the Pods folder was versioned which doesn't follow CocoaPods best practices.

**Comment by msqr** [comment]
Hi Gian, I'm afraid I don't quite understand your question. What exactly do you see that you think should be different or is causing problems?

**Comment by gfzabarino** [comment]
Hi @msqr, I don't think it's going to improve the functionality in any way, but I meant regarding code versioning, I'm used to see projects that have defined the dependencies of pods in the podspec, and the an example project that has a Podfile to let people clone the repository being able to download the dependencies by executing `pod install` on the example project. I believe including BRCLucene code in this project will add noise that is not directly related to this project (my understanding is that you devided the project to let each one mind its own purpose, if that makes sense to you). Let me know if this makes sense now. Thanks for this great project!

**Comment by msqr** [comment]
The `BRCLucene` split can be traced back to https://github.com/Blue-Rocket/clucene/pull/1, as a way for people using `BRFullTextSearch` a way to customize the underlying CLucene used. So this project now depends on `BRCLucene` to compile and that is why it is included. The raw `clucene` code used to be included in this project via a git submodule, so that has now been removed. Basically, that submodule has been replaced by the `BRCLucene` pod.

Does this make sense? I'm not quite sure I'm understanding the point you're raising, so I might be talking about a different angle here?

**Comment by gfzabarino** [comment]
> The BRCLucene split can be traced back to Blue-Rocket/clucene#1, as a way for people using BRFullTextSearch a way to customize the underlying CLucene used. So this project now depends on BRCLucene to compile and that is why it is included. The raw clucene code used to be included in this project via a git submodule, so that has now been removed. Basically, that submodule has been replaced by the BRCLucene pod.

Perfectly understood, and I believe the taken approach is correct.

> Does this make sense? I'm not quite sure I'm understanding the point you're raising, so I might be talking about a different angle here?

Yes it does. What I'm saying is, primarly, dependencies shouldn't be versioned in client projects (not even in libraries).

As I said before, the suggested approach to handle dependencies is to declare them in the podspec, have a Podfile and an example project, and have users install them by running `pod install`. That should be the trigger functionality to download dependecies.

A reasoning for this approach is that if you want to change the dependency's version used in the client project, all you should do is to modify its version in the podspec, but you shouldn't have to also sync the changes of the dependency and version them under the client project. That's the noise I was mentioning, as for a simple operation as changing the dependency's version, a PR would also include potentially many changes from the dependency. In the end, each project should version its own changes, and not the other's.

Answering to your previous question:

> What exactly do you see that you think should be different...

The change I'm thinking would be to remove and add to `.gitignore` the `Pods` folder.

I hope this makes more sense now. Thanks.

**Comment by msqr** [comment]
Ah ok, I understand what you mean, thanks for explaining. I personally prefer having the `Pods` and `Podfile.lock` files added to source control, because development is easier (especially when switching branches). It does add "noise" to this repo, as you mention, but I believe when you do a `pod install` you only get the files included in the podspec, not all the files in the repo. Meaning, if in your own project, after running `pod install` you `ls Pods/BRFullTextSearch` you won't see another `Pods` folder there.

And you _can_ still override the `BRCLucene` dependency to whatever version you want by simply adding it to your project's `Podfile`, e.g. if you wanted a `2.1` release you could have:

```ruby
pod 'BRCLucene', '2.1'
pod 'BRFullTextSearch', '2.0.0-beta1'
```

Another developer [summed up nicely](https://www.dzombak.com/blog/2014/03/including-pods-in-source-control.html) his experiences after starting to commit his `Pods` directory to source control, and I've found I feel similarly.

**Comment by msqr** [comment]
Hi @gfzabarino I wondered if this old discussion is finished for you?

**Comment by gfzabarino** [comment]
Yes, definitely, thanks for asking. I thought it was a mistake but since it’s something made in purpose I believe is good.

**Comment by msqr** [comment]
Great! I'll close the issue then :)
