### ISSUE TITLE
xcode debugger doesn't work?

### ISSUE THREAD

**Issue by andrei4002** [Blue-Rocket/BRFullTextSearch#3]
I'm running the SampleCocoaPodsProject and everywhere I'm trying to debug, I can't seem to be able to access local variables in the debugger (if I try to 'po some_local_var'). It gives some 'Couldn't materialize: couldn't get the value of variable --some var name goes here-- : variable not available
Errored out in Execute, couldn't PrepareToExecuteJITExpression' error.

I tried doing a separate project and it's the same issue, everything works in the debugger until i add this library and use it.

In the project settings, I looked at compiler flags, optimizations, stuff like that, to be set correctly (no optimizations etc), but didn't find anything wrong with them

Any ideas on why is this happening?

**Comment by msqr** [comment]
The Podfile does indeed set the compiler optimization level to -O1, and the sample project did not override that for debug builds. I pushed 249df43 to address your direct issue, if you pull down the latest it should fix the problem for you.

I need to look at if I can drop the optimization level from the Podfile altogether. That was set because we noticed a lot of strange crashes in CLucene that went away when we forced -O1 (rather than -Os).
